ALTER TABLE orders 
ADD COLUMN first_name VARCHAR(100),
ADD COLUMN last_name VARCHAR(100),
ADD COLUMN phone2 VARCHAR(20),
ADD COLUMN wilaya VARCHAR(100),
ADD COLUMN commune VARCHAR(100),
ADD COLUMN delivery_type VARCHAR(50) DEFAULT 'domicile',
ADD COLUMN stop_desk_agency VARCHAR(100),
ADD COLUMN is_free_delivery BOOLEAN DEFAULT FALSE,
ADD COLUMN has_exchange BOOLEAN DEFAULT FALSE,
ADD COLUMN has_insurance BOOLEAN DEFAULT FALSE,
ADD COLUMN declared_value NUMERIC(10, 2);
