// 58 Wilayas of Algeria
export const wilayas = [
  { id: '01', name: 'Adrar' },
  { id: '02', name: 'Chlef' },
  { id: '03', name: 'Laghouat' },
  { id: '04', name: 'Oum El Bouaghi' },
  { id: '05', name: 'Batna' },
  { id: '06', name: 'Béjaïa' },
  { id: '07', name: 'Biskra' },
  { id: '08', name: 'Béchar' },
  { id: '09', name: 'Blida' },
  { id: '10', name: 'Bouira' },
  { id: '11', name: 'Tamanrasset' },
  { id: '12', name: 'Tébessa' },
  { id: '13', name: 'Tlemcen' },
  { id: '14', name: 'Tiaret' },
  { id: '15', name: 'Tizi Ouzou' },
  { id: '16', name: 'Alger' },
  { id: '17', name: 'Djelfa' },
  { id: '18', name: 'Jijel' },
  { id: '19', name: 'Sétif' },
  { id: '20', name: 'Saïda' },
  { id: '21', name: 'Skikda' },
  { id: '22', name: 'Sidi Bel Abbès' },
  { id: '23', name: 'Annaba' },
  { id: '24', name: 'Guelma' },
  { id: '25', name: 'Constantine' },
  { id: '26', name: 'Medea' },
  { id: '27', name: 'Mostaganem' },
  { id: '28', name: 'M Sila' },
  { id: '29', name: 'Mascara' },
  { id: '30', name: 'Ouargla' },
  { id: '31', name: 'Oran' },
  { id: '32', name: 'El Bayadh' },
  { id: '33', name: 'Illizi' },
  { id: '34', name: 'Bordj Bou Arreridj' },
  { id: '35', name: 'Boumerdès' },
  { id: '36', name: 'El Tarf' },
  { id: '37', name: 'Tindouf' },
  { id: '38', name: 'Tissemsilt' },
  { id: '39', name: 'El Oued' },
  { id: '40', name: 'Khenchela' },
  { id: '41', name: 'Souk Ahras' },
  { id: '42', name: 'Tipaza' },
  { id: '43', name: 'Mila' },
  { id: '44', name: 'Aïn Defla' },
  { id: '45', name: 'Naâma' },
  { id: '46', name: 'Aïn Témouchent' },
  { id: '47', name: 'Ghardaïa' },
  { id: '48', name: 'Relizane' },
  { id: '49', name: 'Timimoun' },
  { id: '50', name: 'Bordj Badji Mokhtar' },
  { id: '51', name: 'Ouled Djellal' },
  { id: '52', name: 'Béni Abbès' },
  { id: '53', name: 'In Salah' },
  { id: '54', name: 'In Guezzam' },
  { id: '55', name: 'Touggourt' },
  { id: '56', name: 'Djanet' },
  { id: '57', name: "El M'Ghair" },
  { id: '58', name: 'El Meniaa' }
];

// Mapping to default principal communes. Users can type custom commune via the "Autre" feature implemented in UI
export const communesByWilaya = {
  '01': ['Adrar', 'Reggane', 'Timimoun'],
  '02': ['Chlef', 'Ténès', 'Oued Fodda'],
  '03': ['Laghouat', 'Aflou', "Hassi R'Mel"],
  '04': ['Oum El Bouaghi', 'Aïn Beïda', "Aïn M'lila"],
  '05': ['Batna', 'Barika', 'Arris'],
  '06': ['Béjaïa', 'Akbou', 'Amizour'],
  '07': ['Biskra', 'Sidi Okba', 'Tolga'],
  '08': ['Béchar', 'Abadla', 'Beni Ounif'],
  '09': ['Blida', 'Boufarik', 'El Affroun'],
  '10': ['Bouira', 'Lakhdaria', 'Sour El Ghozlane'],
  '11': ['Tamanrasset', 'In Salah', 'Tazrouk'],
  '12': ['Tébessa', 'Bir el Ater', 'Cheria'],
  '13': ['Tlemcen', 'Maghnia', 'Mansourah'],
  '14': ['Tiaret', 'Sougueur', 'Frenda'],
  '15': ['Tizi Ouzou', 'Azazga', 'Draa El Mizan'],
  '16': ['Alger Centre', 'Bab El Oued', 'Rouiba', 'Hydra', 'El Biar'],
  '17': ['Djelfa', 'Ain Oussera', 'Hassi Bahbah'],
  '18': ['Jijel', 'Taher', 'El Milia'],
  '19': ['Sétif', 'El Eulma', 'Ain Arnat'],
  '20': ['Saïda', 'Hassasna', 'Ain El Hadjar'],
  '21': ['Skikda', 'Azzaba', 'Collo'],
  '22': ['Sidi Bel Abbès', 'Sfisef', 'Telagh'],
  '23': ['Annaba', 'El Bouni', 'Berrahal'],
  '24': ['Guelma', 'Bouchegouf', 'Oued Zenati'],
  '25': ['Constantine', 'El Khroub', 'Ali Mendjeli', 'Hamma Bouziane'],
  '26': ['Médéa', 'Berrouaghia', 'Ksar El Boukhari'],
  '27': ['Mostaganem', 'Aïn Nouïssy', 'Hassi Mameche'],
  '28': ["M'Sila", 'Bou Saâda', 'Magra'],
  '29': ['Mascara', 'Sig', 'Mohammadia'],
  '30': ['Ouargla', 'Hassi Messaoud', 'Touggourt'],
  '31': ['Oran', 'Es Senia', 'Bir El Djir', 'Arzew'],
  '32': ['El Bayadh', 'Bougtob', 'El Abiodh Sidi Cheikh'],
  '33': ['Illizi', 'Djanet', 'In Amenas'],
  '34': ['Bordj Bou Arreridj', 'Ras El Oued', 'Bordj Zemoura'],
  '35': ['Boumerdès', 'Boudouaou', 'Dellys'],
  '36': ['El Tarf', 'El Kala', 'Besbes'],
  '37': ['Tindouf', 'Oum el Assel'],
  '38': ['Tissemsilt', 'Theniet El Had', 'Ammari'],
  '39': ['El Oued', 'Guemar', 'Robbah'],
  '40': ['Khenchela', 'Kais', 'Chechar'],
  '41': ['Souk Ahras', 'Sedrata', 'Taoura'],
  '42': ['Tipaza', 'Bou Ismaïl', 'Cherchell'],
  '43': ['Mila', 'Chelghoum Laïd', 'Ferdjioua'],
  '44': ['Aïn Defla', 'Khemis Miliana', 'Miliana'],
  '45': ['Naâma', 'Mecheria', 'Aïn Séfra'],
  '46': ['Aïn Témouchent', 'Beni Saf', 'Hammam Bou Hadjar'],
  '47': ['Ghardaïa', 'Metlili', 'El Guerrara'],
  '48': ['Relizane', 'Oued Rhiou', 'Mazouna'],
  '49': ['Timimoun', 'Aougrout', 'Charouine'],
  '50': ['Bordj Badji Mokhtar', 'Timiaouine'],
  '51': ['Ouled Djellal', 'Sidi Khaled', 'Chaiba'],
  '52': ['Béni Abbès', 'Igli', 'Kerzaz'],
  '53': ['In Salah', 'In Ghar', 'Foggaret Ezzaouia'],
  '54': ['In Guezzam', 'Tin Zaouatine'],
  '55': ['Touggourt', 'Temacine', 'Megarine'],
  '56': ['Djanet', 'Bordj El Houasse'],
  '57': ["El M'Ghair", 'Djamaa', 'Oum Touyour'],
  '58': ['El Meniaa', 'Hassi Gara', 'Mansoura']
};
